<?php
/**
 * Project: psf
 * User: Brendan Doyle / brendan@2cloud.ie
 * Date: 10/07/2019
 * Time: 18:18
 */

class Demo extends \App\Model
{


    public function show_list()
    {

        return array(
            array("name" => "Barclay Cleveland"),
            array("name" => "Phelan Valdez"),
            array("name" => "Neil Bennett"),
            array("name" => "Daquan Shaffer"),
            array("name" => "Solomon Owens"),
            array("name" => "Blake Salinas"),
            array("name" => "Allen Boyer"),
            array("name" => "Ryder Conrad"),
            array("name" => "Clark Holcomb"),
            array("name" => "Perry Shannon"),
            array("name" => "Tyrone Dodson"),
            array("name" => "Brenden Craft"),
            array("name" => "Declan Dean"),
            array("name" => "Finn Klein"),
            array("name" => "Cadman Yang"),
            array("name" => "Steel Stone"),
            array("name" => "Sylvester Medina"),
            array("name" => "Gage Richardson"),
            array("name" => "Lance Mays"),
            array("name" => "Gage Zamora"),
            array("name" => "Dorian Hebert"),
            array("name" => "Raymond Norman"),
            array("name" => "Melvin Williams"),
            array("name" => "Noble Greene"),
            array("name" => "Merrill Pacheco"),
            array("name" => "Steven Diaz"),
            array("name" => "Curran Bird"),
            array("name" => "Jack Hobbs"),
            array("name" => "Victor Olsen"),
            array("name" => "Emery Woods"),
            array("name" => "Brent Farley"),
            array("name" => "Kermit Wall"),
            array("name" => "Mason Johnston"),
            array("name" => "Dillon Phelps"),
            array("name" => "Benjamin Manning"),
            array("name" => "Boris Moran"),
            array("name" => "Grady Floyd"),
            array("name" => "Martin Levy"),
            array("name" => "Lewis England"),
            array("name" => "Talon Griffin"),
            array("name" => "Jackson Acosta"),
            array("name" => "Jack Cardenas"),
            array("name" => "Hunter Clemons"),
            array("name" => "Jared Landry"),
            array("name" => "Phillip Hogan"),
            array("name" => "Garth Johns"),
            array("name" => "Yasir Ingram"),
            array("name" => "Oliver Schneider"),
            array("name" => "Salvador Shannon"),
            array("name" => "Eric Charles"),
            array("name" => "Deacon Lloyd"),
            array("name" => "Keith Lawrence"),
            array("name" => "Chase Hancock"),
            array("name" => "Damon Brady"),
            array("name" => "Kibo Mueller"),
            array("name" => "Leo Alston"),
            array("name" => "Dominic Anthony"),
            array("name" => "Hamilton Espinoza"),
            array("name" => "Wyatt Patterson"),
            array("name" => "Alexander Clemons"),
            array("name" => "Oleg Curry"),
            array("name" => "Felix Calhoun"),
            array("name" => "Elmo Galloway"),
            array("name" => "Grady Shields"),
            array("name" => "Nissim Stein"),
            array("name" => "Vincent Holloway"),
            array("name" => "Jameson Oneill"),
            array("name" => "Kaseem Blake"),
            array("name" => "Timon Holcomb"),
            array("name" => "Tobias Franklin"),
            array("name" => "Wade Reeves"),
            array("name" => "Stuart Rush"),
            array("name" => "Sawyer Fletcher"),
            array("name" => "Jin Guthrie"),
            array("name" => "Elvis Brennan"),
            array("name" => "Alden Hawkins"),
            array("name" => "Cullen Neal"),
            array("name" => "Carter Peters"),
            array("name" => "Phillip Black"),
            array("name" => "Edan Ingram"),
            array("name" => "Hu Rowland"),
            array("name" => "Drew Booker"),
            array("name" => "Beau Graham"),
            array("name" => "Sean Barnes"),
            array("name" => "Marshall Terrell"),
            array("name" => "Cruz Robbins"),
            array("name" => "Walker Abbott"),
            array("name" => "Joshua Fisher"),
            array("name" => "Cullen Thornton"),
            array("name" => "Brent Fernandez"),
            array("name" => "Barclay Shannon"),
            array("name" => "Valentine Warner"),
            array("name" => "Chester Bolton"),
            array("name" => "Burke Frederick"),
            array("name" => "Melvin Hunt"),
            array("name" => "Michael Sellers"),
            array("name" => "Berk Sampson"),
            array("name" => "Holmes Fowler"),
            array("name" => "Timothy Mcintosh"),
            array("name" => "Hop Vega")
        );


    }
}